### ISSUE TITLE
Endless loop - Node MCU fails to start properly after download

### ISSUE THREAD

**Issue by fadidar** [AWSW-de/WordClock-16x8-LED-matrix#16]
.
.
.
. 
######################################################################
# WordClock startup of version: V3.9.0
######################################################################
ets Jul 29 2019 12:21:46

rst:0x8 (TG1WDT_SYS_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0030,len:4604
ho 0 tail 12 room 4
load:0x40078000,len:15488
load:0x40080400,len:4
load:0x40080404,len:3180
entry 0x400805b8
. 
.
.
![image](https://github.com/user-attachments/assets/d9e50a61-2294-48cb-8b08-0a60df1f4017)

![image](https://github.com/user-attachments/assets/f02d46a6-f1ae-4244-b261-3ee5451f1eb6)

**Comment by AWSW-de** [comment]
Check FAQ please and make sure to use the named libraries and ESP32 board libraries in the named versions. Then it will work
https://www.printables.com/model/749967-wordclock-16x8-2024
You seem to have used the autoupdate in Arduino IDE which updates the ESP32 board lib to a unsupported version as well as the ESPUI library too. Then you get such effects.

**Comment by fadidar** [comment]
Thanks! It works now.

**Comment by fadidar** [comment]
Thanks! It works now.
